import type {
  ActiveHotspotUser,
  ConnectionTestResult,
  HotspotProfile,
  HotspotServer,
  HotspotUser,
  Interface,
  IpAddress,
  LogEntry,
  RouterOsVersion,
  SystemHealth,
  SystemResource,
  UserPolicies,
} from './types.js';
import type { RemoteAccessStep } from './setup-script.js';

/**
 * Phase 1 surface: reads only. Hotspot user writes (create/update/delete/
 * enable/disconnect) arrive in Phase 2 as a separate `HotspotUserWriter`
 * interface so this one is extended, not rewritten (see docs/DECISIONS.md).
 *
 * Every method returns typed data or throws a MikrotikError.
 */
export interface MikrotikProvider {
  connect(): Promise<void>;
  disconnect(): Promise<void>;
  testConnection(): Promise<ConnectionTestResult>;

  getSystemResource(): Promise<SystemResource>;
  getIdentity(): Promise<{ name: string }>;
  getRouterOsVersion(): Promise<RouterOsVersion>;
  getInterfaces(): Promise<Interface[]>;
  getIpAddresses(): Promise<IpAddress[]>;

  getHotspotServers(): Promise<HotspotServer[]>;
  getHotspotProfiles(): Promise<HotspotProfile[]>;
  getHotspotUsers(): Promise<HotspotUser[]>;
  getActiveHotspotUsers(): Promise<ActiveHotspotUser[]>;

  getLogs(opts?: { limit?: number }): Promise<LogEntry[]>;
  getSystemHealth(): Promise<SystemHealth>;

  /** Group and policies of the user we are logged in as — powers "test permissions". */
  getCurrentUserPolicies(): Promise<UserPolicies>;
}

/**
 * The one write Phase 1 performs, kept out of `MikrotikProvider` so the read
 * surface stays read-only (see docs/DECISIONS.md D23).
 *
 * It applies the WireGuard tunnel to a router the connector can already reach,
 * which is how a router added on the local network becomes reachable remotely
 * without anyone pasting a script. Every step is idempotent: running it twice
 * updates the same rows rather than duplicating them.
 */
export interface RemoteAccessWriter {
  /**
   * Applies `steps` and returns the router's WireGuard public key. The private
   * key is generated by the router and never leaves it.
   */
  enableRemoteAccess(steps: readonly RemoteAccessStep[]): Promise<{ publicKey: string }>;
}

export function isRemoteAccessWriter(p: MikrotikProvider): p is MikrotikProvider & RemoteAccessWriter {
  return typeof (p as Partial<RemoteAccessWriter>).enableRemoteAccess === 'function';
}

export const DEFAULT_TIMEOUT_MS = 10_000;
export const DEFAULT_LOG_LIMIT = 100;
export const MAX_LOG_LIMIT = 1000;

export function clampLogLimit(limit: number | undefined): number {
  const n = Math.trunc(limit ?? DEFAULT_LOG_LIMIT);
  if (!Number.isFinite(n) || n < 1) return DEFAULT_LOG_LIMIT;
  return Math.min(n, MAX_LOG_LIMIT);
}
